### ISSUE TITLE
报了个错，项目没跑起来

### ISSUE THREAD

**Issue by siren-ocean** [izzyleung/ZhihuDailyPurify#34]
➜  ZhihuDailyPurify-master bazel build //...
ERROR: /Users/siren/Downloads/ZhihuDailyPurify-master/third_party/BUILD:50:1: no such package '@rxjava//jar': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_siren/b41c16386144de65adf33e9b88dbf0cd/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 288
		_maven_artifact_impl(ctx, "jar", _maven_jar_build_file_te...)
	File "/private/var/tmp/_bazel_siren/b41c16386144de65adf33e9b88dbf0cd/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 237, in _maven_artifact_impl
		_check_dependencies(ctx)
	File "/private/var/tmp/_bazel_siren/b41c16386144de65adf33e9b88dbf0cd/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 58, in _check_dependencies
		fail(("%s requires %s as a dependency...)))
rxjava requires mvn as a dependency. Please check your PATH. and referenced by '//third_party:news_fetch_android_dependencies'
ERROR: Analysis of target '//third_party:news_fetch_android_dependencies' failed; build aborted: no such package '@rxjava//jar': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_siren/b41c16386144de65adf33e9b88dbf0cd/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 288
		_maven_artifact_impl(ctx, "jar", _maven_jar_build_file_te...)
	File "/private/var/tmp/_bazel_siren/b41c16386144de65adf33e9b88dbf0cd/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 237, in _maven_artifact_impl
		_check_dependencies(ctx)
	File "/private/var/tmp/_bazel_siren/b41c16386144de65adf33e9b88dbf0cd/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 58, in _check_dependencies
		fail(("%s requires %s as a dependency...)))
rxjava requires mvn as a dependency. Please check your PATH.
INFO: Elapsed time: 0.346s
FAILED: Build did NOT complete successfully (3 packages loaded)
    currently loading: @bazel_tools//tools/jdk ... (3 packages)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
不知道是不是路径引用失败，报了这个错

**Comment by izzyleung** [comment]
这个错误是因为 bazel 需要 Maven 以下载 Java 的依赖。

通过 `brew install maven` 这个命令安装 Maven 后，错误应该消失。

**Comment by siren-ocean** [comment]
ZhihuDailyPurify-master bazel build //...
............
ERROR: /private/var/tmp/_bazel_siren/152ca77bc66efe87f07b02bae3565757/external/com_google_protobuf/BUILD:180:1: in objc_library rule @com_google_protobuf//:protobuf_objc: Expected action_config for 'objc-compile' to be configured
ERROR: Analysis of target '//proto:zhihu_daily_purify_objc_proto' failed; build aborted: Analysis of target '@com_google_protobuf//:protobuf_objc' failed; build aborted
INFO: Elapsed time: 6.609s
FAILED: Build did NOT complete successfully (53 packages loaded)

@izzyleung 感谢回复，maven之后还报了个问题，有关Objective-C ?

**Comment by izzyleung** [comment]
请确保您已经安装了 XCode，并且已更新至最新的版本。

另外，请确保在命令行执行命令：`xcode-select --install`。

**Comment by siren-ocean** [comment]
![1526911525662](https://user-images.githubusercontent.com/11606702/40311658-182074b4-5d43-11e8-9f96-066781323cfc.jpg)
@izzyleung   我的xcode确实已经安装，不过这个错误并没有消失。

**Comment by izzyleung** [comment]
很抱歉，我没有办法在我的个人和工作的 Mac 上重现这个问题。

根据 Bazel 的输出，我大概可以推断这是一个 CrossTool 配置的问题。
我建议您在 github.com/bazelbuild/bazel/issues 或者在 Bazel 的 Mailing List 寻求帮助。

不过如果您只是需要编译 Android app，您可以在项目的根目录下执行这个命令：`bazel build android`

以下几个 Check point 供您参考：
- 确保 Bazel 已被更新至最新的版本：`brew upgrade bazel`
- 确保在 macOS Sierra 或是 macOS High Sierra 下执行 `bazel build //...`
- 确保可以打开 Xcode 并已安装了 Suggested Components

**Comment by siren-ocean** [comment]
@izzyleung   非常感谢，在使用bazel clean --expunge之后，编译正常通过。
